export const submissionObject = [
    {   id :"1",
        first_name : "The Solar System",
        last_name:"The Solar System" ,
        avatar:"abc",
        content:"full assignment",
        submitted_at: "05/21/17" },
    {   id :"1",
        first_name : "The  System",
        last_name:"The Solar System" ,
        avatar:"abc",
        content:"nill assignment",
        submitted_at: "05/21/17" },
  {   id :"1",
        first_name : "The Solystem",
        last_name:"The Solar System" ,
        avatar:"abc",
        content:"half assignment",
        submitted_at: "05/21/17" },
    {   id :"1",
        first_name : "The Solar System",
        last_name:"The to System" ,
        avatar:"abc",
        content:"total assignment",
        submitted_at: "05/21/17" }

]